title: DevRoutine 개인정보 처리방침
description: DevRoutine 앱의 개인정보 처리방침을 안내합니다.
author: gyhmac
email: gyhmac@gmail.com
url: https://gyhcom.github.io/devroutine

# GitHub Pages 설정
github:
  repository_name: devroutine
  owner_name: gyhcom

# Jekyll 설정
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 언어 설정
lang: ko-KR
timezone: Asia/Seoul

# 제외할 파일/폴더
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 색상 설정 (앱 테마에 맞춤)
color_primary: "#2188FF"
color_secondary: "#4EC9B0"
color_background: "#1E1E1E" 